---
# tasks file for ansible-role-zero-footprint-ruT-seedbox/00-preflight

- name: PREFLIGHT | 0.1 Ensure 'fail2ban_ignore_ipv4' does not contain \
        placeholder 'X.X.X.X'
  ansible.builtin.fail:
    msg: >-
      The 'fail2ban_ignore_ipv4' variable contains a placeholder (X.X.X.X).
      Please replace it with a valid IPv4 address first!
  when: "'X.X.X.X' in fail2ban_ignore_ipv4"
  tags:
    - common
    - preflight

- name: PREFLIGHT | 0.2 Get status of local users.txt file for vsftpd
  ansible.builtin.stat:
    path: "{{ ansible_role_name }}/files/vsftpd/users.txt"
  register: users_txt_stat_result
  delegate_to: localhost
  run_once: true
  when: not single_user
  tags:
    - common
    - preflight

- name: PREFLIGHT | 0.3 Ensure users.txt exists and is not empty for \
        multi-user vsftpd setup
  ansible.builtin.fail:
    msg: >-
      For multi-user vsftpd setup (when single_user is false),
      the file 'files/vsftpd/users.txt' must exist and not be empty.
      Please add users and passwords to this file!
  when:
    - not single_user
    - not users_txt_stat_result.stat.exists or
      users_txt_stat_result.stat.size == 0
  tags:
    - common
    - preflight

- name: PREFLIGHT | 0.4 Read GRUB content
  ansible.builtin.slurp:
    src: "/etc/default/grub"
  register: grub_config_b64
  tags:
    - common
    - preflight

- name: PREFLIGHT | 0.5 Select the relevant line
  ansible.builtin.set_fact:
    grub_line: "{{ (grub_config_b64.content | b64decode).split('\n') \
                | select('match', '^GRUB_CMDLINE_LINUX=') | list }}"
  tags:
    - common
    - preflight

- name: PREFLIGHT | 0.6 Warn if crashkernel is undesirable
  ansible.builtin.fail:
    msg: >-
      WARNING: crashkernel is set in "/etc/default/grub".
      Set "crashkernel=no" and then regenerate GRUB:
      `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` !
  when: >
    (grub_line | lower is search('crashkernel=')) and
    (grub_line | lower is not search('crashkernel=no'))
  tags:
    - common
    - preflight

- name: PREFLIGHT | 0.7 Display GRUB_CMDLINE_LINUX
  ansible.builtin.debug:
    msg: "{{ grub_line }}"
  tags:
    - common
    - preflight
