---
# tasks file for ansible-role-zero-footprint-ruT-seedbox/04-rutorrent

- name: RUTORRENT | 4.1 Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  become: true
  loop:
    - "lighttpd"
    - "lighttpd-fastcgi"
    - "php"
    - "php-dom"
    - "php-fpm"
    - "php-json"
    - "php-mbstring"
    - "php-libxml"
    - "python3-passlib"
  tags:
    - rutorrent

- name: RUTORRENT | 4.2 Remove old ruTorrent folder (for idempotency reasons)
  ansible.builtin.file:
    path: "/var/www/ruTorrent/"
    state: "absent"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.3 Create a directory structure
  ansible.builtin.file:
    path: "/var/www/ruTorrent"
    state: "directory"
    owner: "lighttpd"
    group: "lighttpd"
    mode: "0755"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.4 Untar the ruTorrent sources
  ansible.builtin.unarchive:
    src: "{{ rutorrent_dl }}"
    dest: "/var/www/ruTorrent"
    owner: "lighttpd"
    group: "lighttpd"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "/var/www/ruTorrent/conf/config.php"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.5 Template the configuration for ruTorrent
  ansible.builtin.template:
    src: "rtorrent/config.php.j2"
    dest: "/var/www/ruTorrent/conf/config.php"
    owner: "lighttpd"
    group: "lighttpd"
    backup: true
    mode: "0664"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.6 Ensure unnecessary ruTorrent plugins are disabled
  community.general.ini_file:
    path: "/var/www/ruTorrent/conf/plugins.ini"
    section: "{{ item }}"
    option: "enabled"
    value: "no"
    mode: "0664"
  become: true
  loop:
    - "_cloudflare"
    - "autotools"
    - "dump"
    - "extratio"
    - "extsearch"
    - "feeds"
    - "filedrop"
    - "geoip"
    - "history"
    - "ipad"
    - "lookat"
    - "mediainfo"
    - "ratio"
    - "rss"
    - "rssurlrewrite"
    - "screenshots"
    - "spectrogram"
    - "throttle"
    - "unpack"
    - "uploadeta"
    - "xmpp"
  tags:
    - rutorrent

- name: RUTORRENT | 4.7 Change Plugins from user-defined to yes
  community.general.ini_file:
    path: "/var/www/ruTorrent/conf/plugins.ini"
    section: "default"
    option: "enabled"
    value: "yes"
    mode: "0664"
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.8 Hide the Plugins tab
  community.general.ini_file:
    path: "/var/www/ruTorrent/conf/access.ini"
    section: "tabs"
    option: "showPluginsTab"
    value: "no"
    mode: "0664"
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.9 Copy the configuration for php-fpm
  ansible.builtin.copy:
    src: "lighttpd/www.conf"
    dest: "/etc/php-fpm.d/www.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.10 php-fpm log is sent to syslogd
  ansible.builtin.lineinfile:
    path: "/etc/php-fpm.conf"
    regexp: '^error_log = /var/log/php-fpm/error.log'
    line: "error_log = syslog"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.11 Template the configuration for lighttpd
  ansible.builtin.template:
    src: "lighttpd/lighttpd.conf.j2"
    dest: "/etc/lighttpd/lighttpd.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.12 Copy the configuration for lighttpd modules
  ansible.builtin.copy:
    src: "lighttpd/modules.conf"
    dest: "/etc/lighttpd/modules.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.13 Copy the configuration for auth module
  ansible.builtin.template:
    src: "lighttpd/auth.conf.j2"
    dest: "/etc/lighttpd/conf.d/auth.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.14 Copy the configuration for fastcgi module
  ansible.builtin.copy:
    src: "lighttpd/fastcgi.conf"
    dest: "/etc/lighttpd/conf.d/fastcgi.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.15 Add a user to a htpasswd file and ensure \
        permissions are set
  community.general.htpasswd:
    path: "/var/www/ruTorrent/.htpasswd"
    name: "{{ ansible_user }}"
    password: "{{ htpasswd }}"
    owner: "root"
    group: "lighttpd"
    mode: "0640"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.16 Copy the configuration for proxy module
  ansible.builtin.template:
    src: "lighttpd/proxy.conf.j2"
    dest: "/etc/lighttpd/conf.d/proxy.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.17 Validate the lighttpd config files
  ansible.builtin.command: "lighttpd -t -f {{ item }}"
  args:
    chdir: "/etc/lighttpd/"
  loop:
    - "lighttpd.conf"
    - "modules.conf"
    - "conf.d/auth.conf"
    - "conf.d/fastcgi.conf"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: false
  tags:
    - rutorrent
