---
# tasks file for ansible-role-zero-footprint-ruT-seedbox/04-rutorrent

- name: RUTORRENT | 4.1 Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  become: true
  loop: "{{ rutorrent_required_rpms }}"
  tags:
    - rutorrent

- name: RUTORRENT | 4.2 Create a directory structure
  ansible.builtin.file:
    path: "{{ rutorrent_path }}"
    state: "directory"
    owner: "lighttpd"
    group: "lighttpd"
    mode: "0755"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.3 Untar the ruTorrent sources
  ansible.builtin.unarchive:
    src: "{{ rutorrent_dl }}"
    dest: "{{ rutorrent_path }}"
    owner: "lighttpd"
    group: "lighttpd"
    remote_src: true
    extra_opts: [--strip-components=1]
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.4 Template the configuration for ruTorrent
  ansible.builtin.template:
    src: "rtorrent/config.php.j2"
    dest: "{{ rutorrent_path }}/conf/config.php"
    owner: "lighttpd"
    group: "lighttpd"
    backup: true
    mode: "0640"
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.5 Ensure unnecessary ruTorrent plugins are disabled
  community.general.ini_file:
    path: "{{ rutorrent_path }}/conf/plugins.ini"
    section: "{{ item }}"
    option: "enabled"
    value: "no"
    mode: "0640"
  become: true
  loop: "{{ rutorrent_disabled_plugins }}"
  tags:
    - rutorrent

- name: RUTORRENT | 4.6 Change Plugins from user-defined to yes
  community.general.ini_file:
    path: "{{ rutorrent_path }}/conf/plugins.ini"
    section: "default"
    option: "enabled"
    value: "yes"
    mode: "0640"
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.7 Hide the Plugins tab
  community.general.ini_file:
    path: "{{ rutorrent_path }}/conf/access.ini"
    section: "tabs"
    option: "showPluginsTab"
    value: "no"
    mode: "0640"
    backup: true
  become: true
  tags:
    - rutorrent

- name: RUTORRENT | 4.8 Copy the configuration for php-fpm
  ansible.builtin.copy:
    src: "lighttpd/www.conf"
    dest: "{{ phpfpm_config_file }}"
    backup: true
    mode: "0644"
  become: true
  notify:
    - "Reload php-fpm"
  tags:
    - rutorrent

- name: RUTORRENT | 4.9 php-fpm log is sent to syslogd
  ansible.builtin.lineinfile:
    path: "/etc/php-fpm.conf"
    regexp: '^error_log = /var/log/php-fpm/error.log'
    line: "error_log = syslog"
  become: true
  notify:
    - "Reload php-fpm"
  tags:
    - rutorrent

- name: RUTORRENT | 4.10 Template the configuration for lighttpd
  ansible.builtin.template:
    src: "lighttpd/lighttpd.conf.j2"
    dest: "{{ lighttpd_config_file }}"
    backup: true
    mode: "0644"
  become: true
  notify:
    - "Reload lighttpd"
  tags:
    - rutorrent

- name: RUTORRENT | 4.11 Copy the configuration for lighttpd modules
  ansible.builtin.copy:
    src: "lighttpd/modules.conf"
    dest: "{{ lighttpd_modules_config_file }}"
    backup: true
    mode: "0644"
  become: true
  notify:
    - "Reload lighttpd"
  tags:
    - rutorrent

- name: RUTORRENT | 4.12 Copy the configuration for auth module
  ansible.builtin.template:
    src: "lighttpd/auth.conf.j2"
    dest: "{{ lighttpd_auth_config_file }}"
    backup: true
    mode: "0644"
  become: true
  notify:
    - "Reload lighttpd"
  tags:
    - rutorrent

- name: RUTORRENT | 4.13 Copy the configuration for fastcgi module
  ansible.builtin.copy:
    src: "lighttpd/fastcgi.conf"
    dest: "{{ lighttpd_fastcgi_config_file }}"
    backup: true
    mode: "0644"
  become: true
  notify:
    - "Reload lighttpd"
  tags:
    - rutorrent

- name: RUTORRENT | 4.14 Add a user to a htpasswd file and ensure \
        permissions are set
  community.general.htpasswd:
    path: "{{ rutorrent_path }}/.htpasswd"
    name: "{{ ansible_user }}"
    password: "{{ htpasswd }}"
    owner: "root"
    group: "lighttpd"
    mode: "0640"
  become: true
  notify:
    - "Reload lighttpd"
  tags:
    - rutorrent

- name: RUTORRENT | 4.15 Copy the configuration for proxy module
  ansible.builtin.template:
    src: "lighttpd/proxy.conf.j2"
    dest: "{{ lighttpd_proxy_config_file }}"
    backup: true
    mode: "0644"
  become: true
  notify:
    - "Reload lighttpd"
  tags:
    - rutorrent

- name: RUTORRENT | 4.16 Validate the lighttpd config files
  ansible.builtin.command: "lighttpd -t -f {{ item }}"
  args:
    chdir: "/etc/lighttpd/"
  loop:
    - "conf.d/auth.conf"
    - "conf.d/fastcgi.conf"
    - "lighttpd.conf"
    - "modules.conf"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: false
  tags:
    - rutorrent
