---
# tasks file for ansible-role-zero-footprint-ruT-seedbox/05-security

- name: SECURITY | 5.1 Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - "firewalld"
    - "fail2ban"
    - "policycoreutils-devel"
  tags:
    - security

- name: SECURITY | 5.2 Ensure SELinux is set to enforcing mode
  ansible.builtin.lineinfile:
    path: "/etc/selinux/config"
    regexp: '^SELINUX='
    line: "SELINUX=enforcing"
  become: true
  tags:
    - security

- name: SECURITY | 5.3 Copy the SELinux modules (for ruTorrent & tmux)
  ansible.builtin.copy:
    src: "selinux/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: "0644"
  loop:
    - "rutorrent.te"
    - "tmux.te"
  tags:
    - security

- name: SECURITY | 5.4 Compile the SELinux modules
  ansible.builtin.command: "make -f /usr/share/selinux/devel/Makefile \
                           {{ item | split(\".\") | first }}.pp"
  args:
    chdir: "/tmp"
  changed_when: true
  loop:
    - "rutorrent.te"
    - "tmux.te"
  tags:
    - security

- name: SECURITY | 5.5 Install the SELinux modules
  ansible.builtin.command: "semodule -i {{ item }}"
  args:
    chdir: "/tmp"
  changed_when: true
  become: true
  loop:
    - "rutorrent.pp"
    - "tmux.pp"
  tags:
    - security

- name: SECURITY | 5.6 Start service firewalld
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
    enabled: true
  become: true
  tags:
    - security

- name: SECURITY | 5.7 Create a new firewalld zone "limited"
  ansible.posix.firewalld:
    zone: "limited"
    source: "{{ fail2ban_ignore_ipv4 }}"
    state: "present"
    permanent: true
  become: true
  notify:
    - "Reload firewalld"
  tags:
    - security

- name: SECURITY | 5.8 Permit traffic in "default" zone for https service
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: "enabled"
  become: true
  notify:
    - "Reload firewalld"
  loop:
    - https
  tags:
    - security

- name: SECURITY | 5.9 Permit traffic in "default" zone for various rtorrent, \
        vsftpd, autobrr ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: "enabled"
  become: true
  notify:
    - "Reload firewalld"
  loop:
    - "{{ rtorrent_port }}/tcp"
    - "{{ rtorrent_port }}/udp"
    - "{{ ftp_port }}/tcp"
    - "{{ pasv_port_range }}/tcp"
  tags:
    - security

- name: SECURITY | 5.10 Deny traffic in "default" zone for cockpit
  ansible.posix.firewalld:
    service: "cockpit"
    permanent: true
    state: "disabled"
  become: true
  notify:
    - "Reload firewalld"
  tags:
    - security

- name: SECURITY | 5.11 Deny ICMP traffic in "default" zone
  ansible.posix.firewalld:
    icmp_block: echo-request,echo-reply
    permanent: true
    state: "enabled"
  become: true
  notify:
    - "Reload firewalld"
  tags:
    - security

- name: SECURITY | 5.12 Permit traffic in "limited" zone for various rtorrent, \
        vsftpd, autobrr ports
  ansible.posix.firewalld:
    zone: "limited"
    port: "{{ item }}"
    permanent: true
    state: "enabled"
  become: true
  notify:
    - "Reload firewalld"
  loop:
    - "{{ rtorrent_port }}/tcp"
    - "{{ rtorrent_port }}/udp"
    - "{{ ftp_port }}/tcp"
    - "{{ pasv_port_range }}/tcp"
  tags:
    - security

- name: SECURITY | 5.13 Permit traffic in "limited" zone for https, sshd service
  ansible.posix.firewalld:
    zone: "limited"
    service: "{{ item }}"
    permanent: true
    state: "enabled"
  become: true
  notify:
    - "Reload firewalld"
  loop:
    - https
    - ssh
  tags:
    - security

- name: SECURITY | 5.14 Template the configuration for SSHD
  ansible.builtin.template:
    src: "sshd/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    backup: true
    mode: "0600"
  become: true
  notify:
    - "Reload sshd"
  tags:
    - security

- name: SECURITY | 5.15 Copy the configuration for Fail2Ban (jail)
  ansible.builtin.copy:
    src: "fail2ban/jail.local"
    dest: "/etc/fail2ban/jail.local"
    backup: true
    mode: "0644"
  become: true
  tags:
    - security

- name: SECURITY | 5.16 Copy the configuration for Fail2Ban (lighttpd)
  ansible.builtin.copy:
    src: "fail2ban/lighttpd-auth.local"
    dest: "/etc/fail2ban/jail.d/lighttpd-auth.local"
    backup: true
    mode: "0644"
  become: true
  tags:
    - security

- name: SECURITY | 5.17 Copy the configuration for Fail2Ban (sshd)
  ansible.builtin.copy:
    src: "fail2ban/sshd.local"
    dest: "/etc/fail2ban/jail.d/sshd.local"
    backup: true
    mode: "0644"
  become: true
  tags:
    - security

- name: SECURITY | 5.18 Template the configuration for Fail2Ban (vsftpd)
  ansible.builtin.template:
    src: "fail2ban/vsftpd.local.j2"
    dest: "/etc/fail2ban/jail.d/vsftpd.local"
    backup: true
    mode: "0644"
  become: true
  tags:
    - security

- name: SECURITY | 5.19 Make exceptions for some IP addresses for Fail2Ban
  ansible.builtin.lineinfile:
    path: "/etc/fail2ban/jail.conf"
    regexp: '^#ignoreip = 127.0.0.1/8 ::1$'
    line: "ignoreip = {{ fail2ban_ignore_ipv4 }}"
    backup: true
  become: true
  tags:
    - security

- name: SECURITY | 5.20 Change logging of Fail2Ban to systemd
  ansible.builtin.lineinfile:
    path: "/etc/fail2ban/fail2ban.conf"
    regexp: '^logtarget =.*'
    line: "logtarget = SYSTEMD-JOURNAL"
  become: true
  tags:
    - security

- name: SECURITY | 5.21 Copy the filter for Fail2Ban (lighttpd-auth)
  ansible.builtin.copy:
    src: "fail2ban/lighttpd-auth.conf"
    dest: "/etc/fail2ban/filter.d/lighttpd-auth.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - security

- name: SECURITY | 5.22 Copy the filter for Fail2Ban (vsftpd)
  ansible.builtin.copy:
    src: "fail2ban/vsftpd.conf"
    dest: "/etc/fail2ban/filter.d/vsftpd.conf"
    backup: true
    mode: "0644"
  become: true
  tags:
    - security

- name: SECURITY | 5.23 Disable shell history
  ansible.builtin.lineinfile:
    path: "/etc/profile"
    regexp: '^HISTSIZE=1000$'
    line: "HISTSIZE=0\nHISTFILE=/dev/null"
    backup: true
  become: true
  tags:
    - security
