---
# tasks file for ansible-role-zero-footprint-ruT-seedbox

- name: REBOOT | 7.1 Set Autobrr service as fact
  ansible.builtin.set_fact:
    autobrr_service: "autobrr@{{ ansible_user }}"
  tags:
    - reboot

- name: REBOOT | 7.2 Enable all required services
  ansible.builtin.systemd:
    state: stopped
    enabled: true
    daemon_reload: true
    name: "{{ item }}"
  become: true
  loop:
    - "{{ autobrr_service }}"
    - "fail2ban"
    - "lighttpd"
    - "php-fpm"
    - "rtorrent"
    - "vsftpd"
  tags:
    - reboot

- name: REBOOT | 7.3 Reboot a machine
  ansible.builtin.reboot:
    reboot_timeout: 1200
  become: true
  when: require_reboot
  tags:
    - reboot

- name: REBOOT | 7.4 Empty audit.log after the reboot (cannot be done before that)
  community.general.filesize:
    path: "/var/log/audit/audit.log"
    size: 0B
  become: true
  tags:
    - reboot
