---
# tasks file for ansible-role-zero-footprint-ruT-seedbox/08-smoke_test

- name: TEST | 8.1 Populate service_facts
  ansible.builtin.service_facts:
  tags:
    - smoke_tests

- name: TEST | 8.2 Print ACTIVE services
  ansible.builtin.debug:
    var: ansible_facts['services'].values() |
          selectattr('state','equalto','active') |
          map(attribute='name') | list
  tags:
    - smoke_tests

- name: TEST | 8.3 Print INACTIVE services
  ansible.builtin.debug:
    var: ansible_facts['services'].values() |
          selectattr('state','equalto','inactive') |
          map(attribute='name') | list
  tags:
    - smoke_tests

- name: TEST | 8.4 Print RUNNING services
  ansible.builtin.debug:
    var: ansible_facts['services'].values() |
          selectattr('state','equalto','running') |
          map(attribute='name') | list
  tags:
    - smoke_tests

- name: TEST | 8.5 Print STOPPED services
  ansible.builtin.debug:
    var: ansible_facts['services'].values() |
          selectattr('state','equalto','stopped') |
          map(attribute='name') | list
  tags:
    - smoke_tests

- name: TEST | 8.6 Print UNKNOWN services
  ansible.builtin.debug:
    var: ansible_facts['services'].values() |
          selectattr('state','equalto','unknown') |
          map(attribute='name') | list
  tags:
    - smoke_tests

- name: TEST | 8.7 Check for port 22 to be open and contain "OpenSSH"
  ansible.builtin.wait_for:
    port: 22
    search_regex: "OpenSSH"
    timeout: 60
  register: test_ssh
  tags:
    - smoke_tests

- name: TEST | 8.8 Check for FTP port to be open and contain "220 Welcome to"
  ansible.builtin.wait_for:
    port: "{{ ftp_port }}"
    search_regex: "220 Welcome to"
    timeout: 60
  register: test_ftp
  tags:
    - smoke_tests

- name: TEST | 8.9 Check for rtorrent port to be open
  ansible.builtin.wait_for:
    port: "{{ rtorrent_port }}"
    timeout: 60
  register: test_rtorrent
  tags:
    - smoke_tests

- name: TEST | 8.10 Check for RPC rtorrent endpoint to be open
  ansible.builtin.uri:
    url: "https://{{ ansible_user }}:{{ htpasswd }}@{{ (ansible_ssh_host | \
          default(ansible_host)) | default(inventory_hostname) }}/plugins/\
          httprpc/action.php"
    return_content: true
    validate_certs: false
  register: test_rpc
  failed_when: "'false' not in test_rpc.content"
  tags:
    - smoke_tests

- name: TEST | 8.11 Check for HTTPS rutorrent port to be open
  ansible.builtin.uri:
    url: "https://{{ ansible_user }}:{{ htpasswd }}@{{ (ansible_ssh_host | \
          default(ansible_host)) | default(inventory_hostname) }}:{{ \
          https_port }}"
    return_content: true
    validate_certs: false
  register: test_https
  failed_when: "'rTorrent' not in test_https.content"
  tags:
    - smoke_tests

- name: TEST | 8.12 Check for Autobrr to be responding
  ansible.builtin.uri:
    url: "https://{{ ansible_user }}:{{ htpasswd }}@{{ (ansible_ssh_host | \
          default(ansible_host)) | default(inventory_hostname) }}/autobrr/"
    return_content: true
    validate_certs: false
  register: test_autobrr
  failed_when: "'autobrr' not in test_autobrr.content"
  tags:
    - smoke_tests

- name: TEST | 8.13 Show the smoke test results
  ansible.builtin.debug:
    msg:
      - "Results:"
      - "########"
      - "SSH:               {{ test_ssh.state }}"
      - "FTP:               {{ test_ftp.state }}"
      - "RTORRENT:          {{ test_rtorrent.state }}"
      - "RTORRENT HTTPRPC:  {{ test_rpc.msg }}"
      - "RUTORRENT:         {{ test_https.msg }}"
      - "AUTOBRR:           {{ test_autobrr.msg }}"
  tags:
    - smoke_tests

- name: TEST | 8.14 Output
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "Autobrr URL:"
      - "https://{{ ansible_user }}:{{ htpasswd }}@{{ (ansible_ssh_host | \
          default(ansible_host)) | default(inventory_hostname) }}/autobrr/"
      - "----------------------------------------------------------------"
      - "ruTorrent URL:"
      - "https://{{ ansible_user }}:{{ htpasswd }}@{{ (ansible_ssh_host | \
          default(ansible_host)) | default(inventory_hostname) }}"
      - "----------------------------------------------------------------"
      - "vsFTPd URL:"
      - "ftps://{{ (ansible_ssh_host | default(ansible_host)) | \
          default(inventory_hostname) }}:{{ ftp_port }}"
      - "----------------------------------------------------------------"
      - "nzb360 Torrent settings URL:"
      - "https://{{ ansible_user }}:{{ htpasswd }}@{{ (ansible_ssh_host | \
          default(ansible_host)) | default(inventory_hostname) }}/plugins\
          /httprpc/action.php"
      - "----------------------------------------------------------------"
  tags:
    - smoke_tests
