---
# tasks file for ansible-role-zero-footprint-ruT-seedbox
- name: MAIN | Include 01-common.yml
  ansible.builtin.include_tasks: 01-common.yml
  tags:
    - common

- name: MAIN | Include 02-rtorrent.yml
  ansible.builtin.include_tasks: 02-rtorrent.yml
  tags:
    - rtorrent

- name: MAIN | Include 03-vsftpd.yml
  ansible.builtin.include_tasks: 03-vsftpd.yml
  tags:
    - vsftpd

- name: MAIN | Include 04-rutorrent.yml
  ansible.builtin.include_tasks: 04-rutorrent.yml
  tags:
    - rutorrent

- name: MAIN | Include 05-security.yml
  ansible.builtin.include_tasks: 05-security.yml
  tags:
    - security

- name: MAIN | Include 06-cleanup.yml
  ansible.builtin.include_tasks: 06-cleanup.yml
  tags:
    - cleanup

- name: MAIN | Include 07-reboot.yml
  ansible.builtin.include_tasks: 07-reboot.yml
  tags:
    - reboot
